### ISSUE TITLE
Error when extract JC4

### ISSUE THREAD

**Issue by redtankbai** [kk49/deca#104]
![image](https://user-images.githubusercontent.com/35935360/83980915-51b5c480-a8e7-11ea-8f83-35cfb1a92b99.png)
tried 2 PC version, got same error here
use decaGUI v0.2.9

let me know if any inform you need, thx

**Comment by kk49** [comment]
The log.txt from the project directory would be helpful. I'm testing it now...

**Comment by redtankbai** [comment]
[log.txt](https://github.com/kk49/deca/files/4743106/log.txt)
here is the log file

**Comment by kk49** [comment]
Thanks! It matches what I found running here, they either they snuck in a new texture format, or the more aggressive texture processing found one deca wasn't loading before. Testing the fix now...

**Comment by kk49** [comment]
Here is a build with a possible fix. It's still processing on my computer, but the error that caused the problem before is fixed.

https://ci.appveyor.com/api/buildjobs/njuspp6g1ruru62h/artifacts/deca_gui-b312.zip

**Comment by kk49** [comment]
One more version, this can be used after the data is processing with b312, it only matters when loading the offending textures...
https://ci.appveyor.com/api/buildjobs/lf8q445axd0tjcf9/artifacts/deca_gui-b313.zip

**Comment by redtankbai** [comment]
thx, gonna test now

**Comment by redtankbai** [comment]
and really appreciate your fast response

**Comment by kk49** [comment]
No worries, let me know if you have any more problems.

**Comment by redtankbai** [comment]
everything working smooth now, thx
