### ISSUE TITLE
Where is 'deca_gui.exe'?

### ISSUE THREAD

**Issue by TheBlessedKettle** [kk49/deca#110]
"No installer, just unzip the release file in some directory and start deca_gui.exe." 
Um what? I looked through the files and couldnt find any deca_gui.exe , so Im kinda confused... 
![deca-master 6_26_2020 1_07_44 AM](https://user-images.githubusercontent.com/67454617/85826151-9e9ff480-b749-11ea-89eb-dad76e74e3bf.png)

**Comment by kk49** [comment]
Releases are located here https://github.com/kk49/deca/releases
The new GitHub makes it a bit harder to find.

**Comment by kk49** [comment]
The discord has a channel #deca-dev to get the latest dev release.
https://discord.com/invite/x5AuPj7

**Comment by TheBlessedKettle** [comment]
Thanks man! I really just want to mod on Generation Zero, but I don't really understand how and was told that I needed this to be able to mod the game or something. Its odd how the most in depth guide to modding is a wikipedia entry that doesn't explain it very well.

**Comment by kk49** [comment]
No problem!
Checkout the discord and look in the #tutorials channel, people have put together some videos. It's a slow discord, but there are also people around there who can help out.
There is also a wiki that is very slowly coming together (https://github.com/kk49/apex_engine_info)

**Comment by kk49** [comment]
I updated the readme to make the release info a bit more front and center and I'm going to close out this issue
