### ISSUE TITLE
UnicodeDecodeError during new project with Second Extinction

### ISSUE THREAD

**Issue by RestrainedRaptor** [kk49/deca#122]
When trying to make new project for Second Extinction pre-season 5 (0.5.0.0) I get multiple UnicodeDecodeErrors that result in a failure. I've validated the game files and even reinstalled to make sure the files are okay, but the result is the same. I've been able to use the tool successfully on all the previous versions of the game but I guess something major changed. Here is the log.

[DecaError.txt](https://github.com/kk49/deca/files/7230452/DecaError.txt)

**Comment by kk49** [comment]
Which version of deca are you using?

**Comment by RestrainedRaptor** [comment]
Version 0.2.12 (b432) which was the latest version when Second Extinction was released. I'll have a try with the new pre-release that you pushed out half an hour ago and see what happens.

**Comment by kk49** [comment]
Cool, let me know I tested it with the version of SE i have access too.

**Comment by RestrainedRaptor** [comment]
OK, I have a new issue. `no such column: content_hash`. Log attached. What version of SE are you using?

[DecaError.txt](https://github.com/kk49/deca/files/7232385/DecaError.txt)

**Comment by kk49** [comment]
Did you erase the entire work directory? The database format has changed, processing will have to start from the scratch. I'm using whatever exists in Steam.

**Comment by RestrainedRaptor** [comment]
My bad! I deleted the archive directory but forgot to delete the work directory too.
It looks like I was able to finish making a new project so nice work. Thanks!
