### ISSUE TITLE
DECA v0.2.13 no longer works on theHunter CoTW Patch 1.74

### ISSUE THREAD

**Issue by noskill24** [kk49/deca#130]
DECA v0.2.13 no longer works on theHunter CoTW Patch 1.74 (Revontuli Coast) since 28 June 2022.

**Comment by kk49** [comment]
v0.2.15 released

**Comment by kk49** [comment]
https://github.com/kk49/deca/releases/tag/v0.2.15

**Comment by noskill24** [comment]
Thank you very much for the fast update.
