### ISSUE TITLE
Breaking change in dependency `zugbruecke`

### ISSUE THREAD

**Issue by s-m-e** [kk49/deca#134]
Hey, the author of [zugbruecke](https://github.com/pleiszenburg/zugbruecke) here. The packages just saw a [major update](https://github.com/pleiszenburg/zugbruecke/blob/master/CHANGES.md#010-2022-09-11).

As of v0.1.0 of `zugbruecke`, [this line](https://github.com/kk49/deca/blob/a6966f1b912fba70010cb8cd8a8758fb99363579/deca/decompress.py#L3) in your package needs to be changed from ...

```python
import zugbruecke as ctypes
```

... to ...

```python
import zugbruecke.ctypes as ctypes
```

**Comment by kk49** [comment]
Thanks!
