### ISSUE TITLE
deca_gui-b536 running slow (starting high-load of CPU) after opening RTPC-files.

### ISSUE THREAD

**Issue by noskill24** [kk49/deca#141]
deca_gui-b536 running slow and starting 100%-load of CPU after opening a large RTPC-files.

Steps to reproduce:
1) Create project for "theHunter CoTW" v2414688 (Latest update 2022 Dec 06).
2) Open "/global/global_animal_types.blo" (double click).

Other RTPC-files are working without any problem.

**Comment by kk49** [comment]
I think that has to do with the size of those files, there is an even bigger one in that directory there /global/global_aesir.blo that stops deca cold, I'm not sure for how long it will take to process. This has to do with how the display of large text fields are displayed in deca. Let me see if Qt offers an MVC solution.

**Comment by kk49** [comment]
Fixed I think...

https://ci.appveyor.com/api/buildjobs/h3dk21pm7ljbrwtw/artifacts/deca_gui-b537.zip

**Comment by noskill24** [comment]
Thanks you very much! It works now.

**Comment by noskill24** [comment]
Hey Krys, BTW this isn't the "flags":

https://github.com/kk49/deca/blob/95f26cd052cf345fe57c27580c646e282b7c8af8/python/deca/deca/ff_adf.py#L681

For metatype == 3, the second UINT32 value in Metadata is the relative offset to the next Metadata in memory buffer. It seems they are using that values for integrity check.
