### ISSUE TITLE
0.2.16 - Unable to start a new project, processing error

### ISSUE THREAD

**Issue by philobyte** [kk49/deca#144]
Hi,
will leave this message although it doesn't seem to me that anybody reads here or cares.

When starting a new project, the processing stops after a while with the error messages attached.

When trying to open the project.json, processing is started anew from scratch and then stops at the exact same spot again.

> 2023-01-28 18:51:22.956284: Manager: "process_adf_initial" with 34954 parameters using 12 processes
> 2023-01-28 18:51:23.167283: ELAPSED TIME: 1828 seconds
> 2023-01-28 18:51:28.167284: ELAPSED TIME: 1833 seconds
> 2023-01-28 18:51:29.947286: Processing: adf5: 0 of 2913 done (0.0%) elapsed   7.0 seconds
> 2023-01-28 18:51:29.951284: process_6: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:33.167312: ELAPSED TIME: 1838 seconds
> 2023-01-28 18:51:33.667310: process_0: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:34.661310: process_4: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:34.745307: process_3: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:34.947308: Processing: adf5: 0 of 11651 done (0.0%) elapsed  12.0 seconds
> 2023-01-28 18:51:35.158309: process_1: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:35.188307: process_5: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:35.192310: process_2: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line
 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:35.448308: process_7: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:35.464307: process_9: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:35.467310: process_8: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:35.469307: process_11: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> 2023-01-28 18:51:35.477306: process_10: EXCEPTION: [<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'table_stringhash'"), ['  File "deca\\db_commands.py", line 1027, in run_mp_vfs_base\n', '  File "deca\\db_commands.py", line 1016, in run\n', '  File "deca\\db_commands.py", line 313, in process_command\n', '  File "deca\\db_commands.py", line 293, in <lambda>\n', '  File "deca\\db_commands.py", line 325, in loop_over_uid_wrapper\n', '  File "deca\\db_commands.py", line 610, in process_adf_initial\n']]
> Traceback (most recent call last):
>   File "deca_gui\main.py", line 462, in project_new
>   File "deca\db_processor.py", line 42, in vfs_structure_new
>   File "deca\db_processor.py", line 72, in vfs_structure_prep
>   File "deca\db_processor.py", line 317, in process
>   File "deca\db_processor.py", line 566, in process_by_ftype_match
>   File "deca\db_commands.py", line 136, in do_map
>   File "deca\db_commands.py", line 267, in mp_issue_commands
> Exception: Manager: PROCESSING FAILED

[log.txt](https://github.com/kk49/deca/files/10527978/log.txt)

**Comment by Kr3m** [comment]
Which release are you using?  Have you encountered the same error with other releases?

**Comment by philobyte** [comment]
I'm using pre-release 0.2.16, as stated in the title of my post. Sorry, should perhaps have repeated that in the post body.

And no, I have not encountered this error before, but I also did not use Deca before. When I started to develop an interest in it, the other pre-releases were already outdated.

**Comment by Kr3m** [comment]
> I'm using pre-release 0.2.16, as stated in the title of my post. Sorry, should perhaps have repeated that in the post body.
> 
> And no, I have not encountered this error before, but I also did not use Deca before. When I started to develop an interest in it, the other pre-releases were already outdated.

I wouldn't necessarily say they're outdated.  That pre-release just came out.  I haven't used it and have had no trouble with any other release in the past.  I'd recommend trying the previous one and see if you encounter the same issue.  It may be a bug with the new release.  If that doesn't work out, at least you can rule it out.

**Comment by Nicanor95** [comment]
I have the same problem, 0.2.15 works fine.

**Comment by kk49** [comment]
Which game?

**Comment by philobyte** [comment]
> Which game?

COTW

**Comment by philobyte** [comment]
> I wouldn't necessarily say they're outdated. That pre-release just came out. I haven't used it and have had no trouble with any other release in the past. I'd recommend trying the previous one and see if you encounter the same issue. It may be a bug with the new release. If that doesn't work out, at least you can rule it out.

Well, I'll try 0.2.15 then. 
But even if that works, will I be able to mod the newest game version of COTW (v2434327) with it? From what I understand, I won't. But this is what I wish to do.

**Comment by philobyte** [comment]
Thanks for fixing. ;)

**Comment by kk49** [comment]
I think this fixes it

https://ci.appveyor.com/api/buildjobs/rj9dwa23xgf89nky/artifacts/deca_gui-b548.zip

**Comment by bertmelis** [comment]
I've downloaded from appveyor and started a new project...

```
sqlite3.OperationalError: no such column: content_hash
```

**Comment by kk49** [comment]
@bertmelis That is probably because the old database was not deleted, delete all the files in the work directory so it can start from scratch

**Comment by Kr3m** [comment]
> > I wouldn't necessarily say they're outdated. That pre-release just came out. I haven't used it and have had no trouble with any other release in the past. I'd recommend trying the previous one and see if you encounter the same issue. It may be a bug with the new release. If that doesn't work out, at least you can rule it out.
> 
> Well, I'll try 0.2.15 then. But even if that works, will I be able to mod the newest game version of COTW (v2434327) with it? From what I understand, I won't. But this is what I wish to do.

For future reference, you don't have to update your deca just because the game updates.  It's nice to have the latest release of course, but the only thing you really have to do when a new update for the game comes out is start a new project since the old one will no longer work.
