### ISSUE TITLE
0.2.18 - Unable to start a new project, processing error - COTW

### ISSUE THREAD

**Issue by mikuyourworld** [kk49/deca#151]
![image](https://github.com/kk49/deca/assets/30253025/b75f5a8f-5881-442a-8f25-143521ec5b5b)

**Comment by mikuyourworld** [comment]
[hplog.txt](https://github.com/kk49/deca/files/13495340/hplog.txt)

**Comment by cagatay117** [comment]
same here.

**Comment by liyxtest** [comment]
same

**Comment by Yvanzk** [comment]
same

**Comment by cagatay117** [comment]
@kk49 Krys could you please advice. I heard that global.gdcc is no longer in use, it is just an empty stub. Modding returned the way it was before global.gdcc, so I think we need updated DECA tool.

**Comment by blazedPhoenix01** [comment]
Seems dog update broke it.

**Comment by liammh7** [comment]
same thing happening here

**Comment by CyberWolf232** [comment]
I believe it was the bloodhound dlc that broke it as well, same problem is occurring with mine.

**Comment by mikuyourworld** [comment]
this has been fixed in b561. Thank you for fixing it.

**Comment by CyberWolf232** [comment]
Where can I find b561? It is not in the updates section.

**Comment by mikuyourworld** [comment]
> Where can I find b561? It is not in the updates section.

You can find it in deca's discord, in the deca-dev channel.

**Comment by kk49** [comment]
https://ci.appveyor.com/api/buildjobs/uv8fxmejirmmqg8a/artifacts/deca_gui-b561.zip

It's a temporary link, I'll see what I can do about that.

**Comment by cagatay117** [comment]
> > Where can I find b561? It is not in the updates section.
> 
> You can find it in deca's discord, in the deca-dev channel.

there's only updated python files in the develop section of the github page, where is the compiled executable?

**Comment by cagatay117** [comment]
> https://ci.appveyor.com/api/buildjobs/uv8fxmejirmmqg8a/artifacts/deca_gui-b561.zip
> 
> It's a temporary link, I'll see what I can do about that.

it says `{"message":"Artifacts download limit (1024 MB/day) exceeded."}` can't download sorry :/

**Comment by kk49** [comment]
Holy crap, I guess people are using deca. I'll start posting interim ones here... brb

**Comment by kk49** [comment]
https://github.com/kk49/deca/releases/tag/daily-202403171200

**Comment by CyberWolf232** [comment]
Omg! This is awesome! Thank you so much, it worked! One more question, where can I view these files to edit them and such? Say I want to go to 3ds max or blender and edit it.
