### ISSUE TITLE
add support for JC4 and Rage2

### ISSUE THREAD

**Issue by redtankbai** [kk49/deca#72]
spend long time to play with Gibbed.JustCause3.Unpack and Gibbed.JustCause4.Unpack, but cannot get most of file placed in correct place with correct name (anim and model are what im looking for ) when work on theHunter COTW

then your tool saved me! it even got texture converted as how beautiful they are!

so could you plz include more game like JC4 and Rage2? it will be a great help!

thanks!

**Comment by kk49** [comment]
It's on the todo list...  I would like to make those work, I bought JC4 for that purpose lol
 
In the mean time have you tried this? https://justcause4mods.com/mods/ashen-mod-tools-for-jc4/ 
They seem to have support for the archive format of JC4 (and probably Rage2). There are also some discords on that link that can lead you to the JC4 mod community

**Comment by redtankbai** [comment]
i tried lots of tools these days and i believe include that one, the thing is most of them cannot get full animation and model list (.ban, .modelc), and only get large number of .hkt files with hashed name

the deca get .ban files with proper names which was great

**Comment by kk49** [comment]
That's good know, I guess that puts more pressure on getting those to work.

**Comment by kk49** [comment]
JC4 (missing file names) and really basic Rage2 (missing FILES, support for the new small/sub archive format has to be added) support are in testing now. 
https://ci.appveyor.com/api/buildjobs/pd1fm6ek8beqtjui/artifacts/deca_gui-b200.zip

**Comment by redtankbai** [comment]
great push, looking forward it been finalized!

**Comment by kk49** [comment]
I'm closing this issue, support for JC4 and RAGE2 now exists, the level of that support is dependent on the individual game and they each have their own issues.

Right now the specific game issues are RAGE2: #92 and JC: #93
