### ISSUE TITLE
GZ map update

### ISSUE THREAD

**Issue by xmstspider** [kk49/deca#98]
Hi,

your GenZero map is (great)[https://kk49.github.io/deca/gz/full.html?no_collapse_layers] but after the developers released latest patch in March it's slightly unsynced.

1. Is it possible to update the map so it's accurate again?
2. Is is possible to generate the map locally?

Thanks

**Comment by kk49** [comment]
1. It should be up to date to the March update, it is missing a schematic because of the way I did the search the first time, I'm fixing that. what is the mismatch you are seeing, it may be a bug.
 
2. It is. If you run deca on GZ and then go to the tools menu and click on make web map... it will generate the map in the working directory. It takes a while, it builds up all the map images and looks through a good chunk of the archives.

**Comment by kk49** [comment]
2. However schematic finding isn't in a released deca version, yet... I should make add a realtime dev/test release

**Comment by PicSoul** [comment]
Is it possible to generate maps from CoTW? I gave it a shot yesterday but didn't have much success. I thought maybe it was due to the game having more than one map?

**Comment by kk49** [comment]
Right now it's GZ only. They change the location of various things between games and I haven't yet refactored it to handle the difference like the rest of the code, I didn't have a feel for how the games were laid out originally so it's a bit of a mess. Issue #10 was to add support for other games, I just added #100 for COTW support.

**Comment by PicSoul** [comment]
Thank you for the explanation. Even without some of the functionality, I'm having a blast digging through files and learning things. Thank you for all the effort you have put into this! :-)

**Comment by kk49** [comment]
I put up the latest version of the map. Now with loot items. So if you can't see the loot items, something may be caching an old version.

**Comment by xmstspider** [comment]
>     1. It should be up to date to the March update, it is missing a schematic because of the way I did the search the first time, I'm fixing that. What is the mismatch you are seeing, it may be a bug.

Thanks. I reloaded the map and now it's showing right (I used the new safehouse at -1329.6, 1025.0, 3651.8 as a reference)

>     2. It is. If you run deca on GZ and then go to the tools menu and click on make web map... it will generate the map in the working directory. It takes a while, it builds up all the map images and looks through a good chunk of the archives.

Nice. Will try that later. Thanks for a great work

**Comment by kk49** [comment]
Cool, let me know if you have any problems with the local processing. Also could you close this issue if you think it's "solved", thanks!

**Comment by xmstspider** [comment]
Thanks
